//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Projekt_UF27ER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raktar
    {
        public int ID { get; set; }
        public string Termek { get; set; }
        public Nullable<int> keszlet_db { get; set; }
        public int Egysegar_ft { get; set; }
        public string Kategoria { get; set; }
        public string Marka { get; set; }
        public string Termek_nev { get; set; }
    }
}
